### PR TITLE
Testing cosypose inference pipeline.

### PR DESCRIPTION
**Pull request by petrikvladimir**

### CODE REVIEW

**Review by nim65s — COMMENTED** [review]
Thanks for this !

tests/data/crackers_example/models/obj_000002.ply is ~1MB and tests/data/crackers_example/models/obj_000002.png is ~10MB, maybe it could be downloaded with the datasets ? 
This might require additional work on the download scripts and a few hosting / mirroring operations, but it can be worth it, and Alice is already looking into this part I think

**Comment by petrikvladimir** [comment]
I didn't realize those files were big. I agree they should not be part of the repository; download script seems a natural solution in the future. However, I would like to not postpone merging this test for a long time, so I moved those files to a separate repository on GitHub and cloned it inside the action. @nim65s, is that an acceptable workaround?

Once we have the download script ready, it can be easily updated in the action. If that is acceptable for merging, please do squash-and-merge so that big files are not kept in repo history.

**Review by nim65s — APPROVED** [review]
Ok for the temporary workaround, thanks !

**Comment by nim65s** [comment]
This was squashed and force-pushed in 03207c77f2e38ea5e0670ec411d9a9951ea25d9f

**Pull request merged**
